language: node_js
node_js:
  - 12

cache:
  npm: false
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn install
  - yarn test
